properties([parameters([ string(defaultValue: '', description: '	Branches to build', name: 'Branch_To_Build', trim: false),string(defaultValue: '', description: '	Checkout to a Sub Directory', name: 'Checkout_To_SubDirectory', trim: false)])])

node()  {

        echo 'Hello World!'
        echo "Branches to build selected : ${params.Branch_To_Build}"
        echo "Checkout to SubDirectory selected : ${params.Checkout_To_SubDirectory}"
      
      if ( params.Branch_To_Build == "Milestone1")
    {
        echo "Inside if"
        SubDirToCheckout = 'super/'+params.Branch_To_Build
        echo "Checkout to SubDirToCheckout is   "
        echo SubDirToCheckout
        
    }
      else
    {
        echo "Inside if"
        
        SubDirToCheckout = params.Branch_To_Build
        
        echo "Checkout to SubDirToCheckout  is  "
        echo SubDirToCheckout
        
    }

    stage('Checkout')
    {
        checkout([$class: 'GitSCM', branches: [[name: params.Branch_To_Build]], doGenerateSubmoduleConfigurations: false, extensions: [[$class: 'CleanBeforeCheckout'],  [$class: 'RelativeTargetDirectory', relativeTargetDir: SubDirToCheckout]], submoduleCfg: [], userRemoteConfigs: [[url: 'https://github.com/rsundara3/APIProject.git']]])

        echo env.GIT_COMMIT
        echo env.GIT_BRANCH 
        echo env.GIT_REVISION        
    }
           
  
}	
